### ISSUE TITLE
Why does my routing conflict

### ISSUE THREAD

**Issue by justhzd** [Rust-Book-Collective/rust-api-dev#6]
```rust
pub fn configure(state: Arc<ApplicationState>) -> Router{
    Router::new()
        .route(
            "/hello",
            get(handlers::index::index).with_state(state.clone()),
        )
        .route(
            "/posts",
            post(handlers::posts::create)
                .with_state(state.clone())
                .route_layer(middleware::from_fn_with_state(state.clone(), auth)),
        )
        .route(
            "/posts",
            get(handlers::posts::list).with_state(state.clone()),
        )
        .route(
            "/posts/:slug",
            get(handlers::posts::get).with_state(state.clone()),
        )
        .route(
            "/posts/:id",
            put(handlers::posts::update)
                .with_state(state.clone())
                .route_layer(middleware::from_fn_with_state(state.clone(), auth)),
        )
        .route(
            "/posts/:id",
            delete(handlers::posts::delete)
                .with_state(state.clone())
                .route_layer(middleware::from_fn_with_state(state.clone(), auth)),
        )
        .route("/login", post(handlers::login::login).with_state(state))
}
```
I used the same code as the example in v1.rs, but when starting the service, why is there an error message saying:
```
Invalid route "/posts/: id": insertion failed due to conflict with previously registered route:/posts/: slug
```
The Axum I am using is 0.7.7
```
[dependencies]
axum = {version = "0.7.7", features = ["default"]}
axum-extra = "0.9.4"
```

**Comment by sapati** [comment]
Axum cannot differentiate the routes /posts/:id and /posts/:slug because essentially they both say /posts/something
Other frameworks allow the use of regexps on the placeholders, so I can ensure that :id is always numeric and the framework uses this path only when the passed argument is numeric and the :slug version otherwise. Axum does not allow this, so we have to use the same placeholder in every variation of the path. Fixed the sample code and the tutorial.

This also means that I cannot have a GET /posts/:id (with numeric id) and GET /posts/:slug (with string slug) at the same time. The only way to solve this situation would be to accept a string in parameter and parse the received string in the handler or in a middleware and do the  decision between an integer id and a string slug there.
